image:
  repository: gongcaedan.kr.ncr.ntruss.com/gongcaedan/api-gateway
  tag: "a4d7e0c"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer   
  port: 8080

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"

  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: "http://eurekaserver:8761/eureka"

  - name: JWT_SECRET_BASE64
    valueFrom:
      secretKeyRef:
        name: gateway-secrets
        key: JWT_SECRET_BASE64
        
resources:
  requests:
    cpu: "200m"
    memory: "384Mi"
  limits:
    cpu: "400m"
    memory: "640Mi"

imagePullSecrets:
  - name: ncr-cred