apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
  labels:
    app: eurekaserver
spec:
  type: {{ .Values.service.type }}
  selector:
    app: eurekaserver
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8761