apiVersion: v1
kind: Service
metadata:
  name: user
  labels: { app: user }
spec:
  type: {{ .Values.service.type }}
  selector: { app: user }
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080