apiVersion: v1
kind: Service
metadata:
  name: candidate
  labels:
    app: candidate
spec:
  type: {{ .Values.service.type }}
  selector:
    app: candidate
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080