image:
  repository: gongcaedan.kr.ncr.ntruss.com/gongcaedan/pledge-tracker
  tag: "f4a0654"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

env:
  # 프로파일 → ConfigMap 참조
  - name: SPRING_PROFILES_ACTIVE
    valueFrom:
      configMapKeyRef:
        name: pledge-tracker-config
        key: SPRING_PROFILES_ACTIVE

  # DB → Secret 참조
  - name: DB_URL
    valueFrom:
      secretKeyRef:
        name: pledge-tracker-db
        key: DB_URL
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: pledge-tracker-db
        key: DB_USERNAME
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pledge-tracker-db
        key: DB_PASSWORD

imagePullSecrets:
  - name: ncr-cred           # 클러스터에 1회 생성하는 docker-registry secret 이름