image:
  repository: registry.kr.ncr.ntruss.com/gongcaedan/pledge-tracker
  tag: "f4a0654"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

env:                          # 필요하면 여기 정의하고 deployment에서 참조
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"

imagePullSecrets:
  - name: ncr-cred           # 클러스터에 1회 생성하는 docker-registry secret 이름