apiVersion: apps/v1
kind: Deployment
metadata:
  name: pledge-tracker
  labels: { app: pledge-tracker }
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: pledge-tracker }
  template:
    metadata:
      labels: { app: pledge-tracker }
    spec:
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      containers:
        - name: pledge-tracker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
          {{- if .Values.env }}
          {{- toYaml .Values.env | nindent 12 }}
          {{- end }}

          {{- if .Values.readinessProbe }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 6 }}
          {{- end }}

          {{- if .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 6 }}
          {{- end }}
          
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 30