image:
  repository: gongcaedan.kr.ncr.ntruss.com/gongcaedan/user
  tag: "42104f7"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer   
  port: 8080

resources:
  requests:
    cpu: "200m"
    memory: "384Mi"
  limits:
    cpu: "400m"
    memory: "640Mi"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"

  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: "http://eurekaserver:8761/eureka"
  
  - name: GOOGLE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: userservice-secrets
        key: GOOGLE_CLIENT_ID

  - name: GOOGLE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: userservice-secrets
        key: GOOGLE_CLIENT_SECRET

  - name: JWT_SECRET_BASE64
    valueFrom:
      secretKeyRef:
        name: userservice-secrets
        key: JWT_SECRET_BASE64

  - name: REDIS_URL
    valueFrom:
      secretKeyRef:
        name: userservice-secrets
        key: REDIS_URL

imagePullSecrets:
  - name: ncr-cred