image:
  repository: gongcaedan.kr.ncr.ntruss.com/gongcaedan/user
  tag: "b63ccdb"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP   
  port: 8080

resources:
  requests:
    cpu: "200m"
    memory: "384Mi"
  limits:
    cpu: "400m"
    memory: "640Mi"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"

  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: "http://eurekaserver:8761/eureka"
  
  - name: DB_URL
    valueFrom:
      secretKeyRef:
        name: userservice-secrets
        key: DB_URL

  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: userservice-secrets
        key: DB_USERNAME

  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: userservice-secrets
        key: DB_PASSWORD

  - name: JWT_SECRET_BASE64
    valueFrom:
      secretKeyRef:
        name: userservice-secrets
        key: JWT_SECRET_BASE64

  - name: REDIS_URL
    valueFrom:
      secretKeyRef:
        name: userservice-secrets
        key: REDIS_URL

imagePullSecrets:
  - name: ncr-cred